version: '3.8'
services:
  redis:
    image: redis
  web:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      FLASK_APP: run
      FLASK_DEBUG: 1
    volumes:
      - .:/app
    command: flask run -h 0.0.0.0 -p 3000
    ports:
      - 8002:3000

  celery:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      FLASK_APP: run
    volumes:
      - .:/app
    command: celery -A run.celery worker --loglevel=info
    depends_on:
      - redis
